### ISSUE TITLE
Refactor TEX file format parsing

### ISSUE THREAD

**Issue by Crauzer** [LeagueToolkit/LeagueToolkit#141]

**Comment by Morilli** [comment]
Riot recently added the `rgba8` format to tex files; which should probably also be supported going forward.
Here are relevant commits from [moonshadow](https://github.com/moonshadow565/ritotex/commit/fe81b5d18aed717c5d4f87debc49cef1909ced4d) and [myself](https://github.com/Morilli/Ritoddstex/commit/07095d5a8bdffb4a102b7489caad52b295052405) that support this.

**Comment by Crauzer** [comment]
https://github.com/LeagueToolkit/LeagueToolkit/pull/210
