### ISSUE TITLE
Missing `libzstd` on 4.0.0-beta.8

### ISSUE THREAD

**Issue by Rerago** [LeagueToolkit/LeagueToolkit#229]
Due to the change from `ZstdSharp.Port` to `ZstdNet` the `libzstd.dll` is needed again. And this is not included in the nuget.
What is the reason against `ZstdSharp`? Seems to be actively in development:

https://github.com/oleg-st/ZstdSharp

**Comment by Crauzer** [comment]
I'm not sure why I switched, I'll switch it back just so I don't have to handle the DLLs

**Comment by Rerago** [comment]
perfect thank you
(I'll leave the issue open as a reminder, you can close it with the commit)

**Comment by Crauzer** [comment]
These kinds of nuget issues really make my veins pop
