### ISSUE TITLE
`GetDataHandle().GetDecompressedStream()` vs `OpenChunk` and `CopyTo`

### ISSUE THREAD

**Issue by Rerago** [LeagueToolkit/LeagueToolkit#231]
So I'm trying to rebuild `LoLWideScreenFix` to the latest version.

Before I could always do the following from the WadEntry to get the stream:

````cs
using var entryDecompressedStream = wadEnt.GetDataHandle().GetDecompressedStream();
````

To achieve the same with the `WadChunk` i need to do the following:

````cs
using var entryDecompressedStream = new MemoryStream();

using var chuckStream = wadFile.OpenChunk(wadChunk);
     chuckStream.CopyTo(entryDecompressedStream);

entryDecompressedStream.Seek(0, SeekOrigin.Begin);
````

Can it be that `OpenChunk ` should do at `Seek(0, SeekOrigin.Begin)` on the start? Because if I don't do seek I can't call e.g. `GetExtensionType` without error, because the stream is already at the end.

**Comment by Crauzer** [comment]
I think I forgot to add an API for this while making it. We can add an API which allocates a `MemoryOwner<byte>` for the decompressed data and copies the data from the decompression stream into it and then returns that to the callee.
