### ISSUE TITLE
Possibility to load `BinTree` with `MemoryOwner<byte>`

### ISSUE THREAD

**Issue by Rerago** [LeagueToolkit/LeagueToolkit#243]
I started to look at the property bin changes (besides, a nuget update would be totally nice). I noticed that `LoadChunkDecompressed` returns a `MemoryOwner<byte>` (see #231). But `BinTree` unfortunately can only be loaded via a `Stream` or a file. 

I think here we would have to make an adjustment at one point. Because either `WadChunk` should get the possibility to return a decompress `Stream` or `BinTree` should get the possibility to be loaded via `MemoryOwner<byte>`.

**Comment by Crauzer** [comment]
The `CommunityToolkit.HighPerformance` package [implements a `AsStream` extension method for `IMemoryOwner<byte>`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.toolkit.highperformance.imemoryownerextensions.asstream?view=win-comm-toolkit-dotnet-7.0#microsoft-toolkit-highperformance-imemoryownerextensions-asstream(system-buffers-imemoryowner((system-byte)))) which allows you to easily "transform" the buffer into a `Stream`, which then also takes care of disposing the memory.

I intend to keep just the `Stream` public reading APIs as I want to allow the callee to have freedom in how they pass in the data.

**Comment by Crauzer** [comment]
There is also [this method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.toolkit.highperformance.memoryextensions.asstream?view=win-comm-toolkit-dotnet-7.0). Which allows you to keep ownership of the memory at the cost of having to track its lifetime.

**Comment by Rerago** [comment]
`AsStream ` worked great. I think we can leave it like this for now.
