### ISSUE TITLE
`GetExtensionType(Stream, int)` returns `Unknown` if the `stream` is at the end

### ISSUE THREAD

**Issue by Rerago** [LeagueToolkit/LeagueToolkit#246]
If you call `GetExtensionType(Stream, int)` when the `stream` has already reached the end, the function always returns `Unknown`.

It looks like `stream.Read(array, 0, array.Length)` simply does not read anything because the `array` is always filled with 0 afterwards. If `stream.Seek(0, SeekOrigin.Begin)` is called before the `stream.Read(array, 0, array.Length)`, everything works so far. Like this:

```cs
public static LeagueFileType GetExtensionType(Stream stream, int headerSizeHint = 8)
{
    byte[] array = new byte[headerSizeHint];
    int num = (int)stream.Position;
    stream.Seek(0, SeekOrigin.Begin);
    stream.Read(array, 0, array.Length);
    stream.Seek(num, SeekOrigin.Begin);
    return Utilities.GetExtensionType(array);
}
```

I would have made a PR. However, I am not sure whether this could not be solved better.

**Comment by Crauzer** [comment]
I think this behavior makes sense. This is an unfortunate side effect of how streams work.

The function cannot make the assumption that the header is actually at the start of the stream. It definitely could, but then someone might make an issue identical to this one but asking about why it's trying to read from the start. It is better make it the callers responsibility to make sure that the stream is positioned correctly, that way there doesn't have to be any enforced behavior.

**Comment by Rerago** [comment]
Ok. But can we then think/talk about a `GetExtension(Span<byte>)` support?

**Comment by Crauzer** [comment]
For sure, I do want to refactor the whole library to make use of C#'s `Span` and `Memory` API so this is definitely a priority.

I think there is a comment somewhere in the file that mentions this as well.

**Comment by Rerago** [comment]
All right, then this one can be closed.
