### ISSUE TITLE
Error loading some parts of the current `UI.wad.client`

### ISSUE THREAD

**Issue by Rerago** [LeagueToolkit/LeagueToolkit#269]
Because of #248 i am still on `4.0.0-beta.4`. Therefore `LoLWideScreenFix` would report the following error:

```
Decompressed content size cannot be determined (e.g. invalid magic number, srcSize too small)
```

Since I wanted to make sure that this was not a bug in the old version, I also tested this in the current version:

```cs
using WadFile wad = new("UI.wad.client");
_ = wad.LoadChunkDecompressed(2458791729318577054);
```

And this code leads to the following error:

```
ZstdSharp.ZstdException: "Unknown frame descriptor"
```

I assume that the error also exists in the current code.

**Comment by Morilli** [comment]
The path corresponding to that hash is `assets/maps/particles/tft/item_icons/standard/blue_buff.tex`. This is unfortunately part of the ongoing `ZstdChunked` compression issue, where data isn't just three back-to-back zstd frames, but rather an uncompressed part followed by two zstd-compressed frames instead.

Unsure how to resolve this in the most correct way, @Crauzer thoughts?

Some ideas:
1. Use the `.subchunktoc` file to figure out which subchunks are compressed and which aren't (requires knowing the existence of + the path to the subchunktoc file though)
2. Assume the first subchunk(s?) may be uncompressed and just read the data raw until the zstd magic number is encountered, and only call zstd from there on out (kinda hacky)
3. Assume any subchunk may be either uncompressed or compressed and do the above process, but repeat until no more data is left and then concatenate all of that (super hacky)
