### ISSUE TITLE
Fbx support for Map and Skin Files

### ISSUE THREAD

**Issue by TheKillerey** [LeagueToolkit/LeagueToolkit#95]
Would be great to have a fbx import / export support. Obj files are limited like I can use only 1 UV.

**Comment by Crauzer** [comment]
I'll probably add glTF support at some point.

Nobody has created a library for creating FBX or DAE files in C# yet.

**Comment by Crauzer** [comment]
Closing this as we now have full fledged support for converting mapgeo to gltf
